### ISSUE TITLE
Blog のコンテンツ作成

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/oystersjp.github.io#10]
Blog のコンテンツ作成

_Originally posted by @cocoeyes02 in https://github.com/oystersjp/oystersjp.github.io/issues/3#issuecomment-487504845_

**Comment by klack710** [comment]
■迷っていること
1. Oystersのグループ用ブログは作るのか
2. もし作らないなら、はてなブログのグループのリンクだけで良い気がする
3. その場合、About usみたいなデザインで、Contactとまとめても良い気がする

1.はまだ要らない気がしている。オープンな活動は活発ではないので、Oystersとしての広報必要？ってなってる。Oysters用twitterアカウント以外に作ってまで書くことあるのかなって。

**Comment by klack710** [comment]
■あらすじ
```
1. Oysters用Blog作る意味ある？
2. 作るとして、どんな目的で作る？
ってのが、自分では思い浮かばなかった。だから作らなくてもいいのでは？

→ブログはブロググループでいい
```
```
ブロググループにするなら、About usみたいなデザインで、Contactとまとめても良い気がする

→contactとblogって見る人は目的違うからまとめるのはすこし微妙じゃない？
```

**Comment by klack710** [comment]
Blogって、見たい人は誰だろう。

今回私達が提供しているのは、Oystersグループのブログではなく、
メンバーのブログ集なので、

1. 導線で呼び込みたい人
2. そのためにどんな導線が必要か
3. どんな機能があればいいか

は考える必要があるかも。
すると、もしかしたら『Blog』って単品で導線を用意するのではなく、
他の導線の形が必要かもしれない。

**Comment by klack710** [comment]
contact

1. 導線で呼び込みたい人
Oystersに入りたい、エンジニア集団に対して興味がある。
そして、サイトの情報だけでは足りないから、連絡が取りたい

2. そのためにどんな導線が必要か
Contactという単体の導線が必要

3. どんな機能があればいいか
リンクをたどった先で、メールやtwitterなどの連絡手段を閲覧者が手に入れる

(たしかに、Blogとまとめるのはよくなさそう)

**Comment by klack710** [comment]
Blog

1. 導線で呼び込みたい人

2. そのためにどんな導線が必要か

3. どんな機能があればいいか
各メンバーのブログが見れる状態

この1.2.の部分が、今私思いつかないので、どなたかアドバイスほしい(T_T)
もし、1.がメンバーを知りたいの場合、Teamの方にブログのリンクを持たせたらいいと思うので、Blogの項目は消えると思う。

**Comment by klack710** [comment]
これについて、他の人の意見とか聞きたいー！

**Comment by cocoeyes02** [comment]
いったんBlogグループのリンクが貼ってあるのでcloseする
