### ISSUE TITLE
Contact のコンテンツ作成

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/oystersjp.github.io#11]
Contact のコンテンツ作成

_Originally posted by @cocoeyes02 in https://github.com/oystersjp/oystersjp.github.io/issues/3#issuecomment-487504959_

**Comment by yutonihei** [comment]
Contactには誰かのTwitterのアカウントを載せますかー？
それともOystersの代表アカウントを作成して、それを載せますか？

**Comment by cocoeyes02** [comment]
個人的には Oysters の代表アカウントを作成して、載せたほうがいいかなと感じます！

誰かの Twitter アカウントを載せると、その人が忙しい時に応答できなくなるので…！
あと、そんなに DM 送ってくる人多くないとは思いますが、万が一多かった時一人に負担が集中するかなと…

ただ Oysters の代表アカウントもみんなで運用するコストは発生するのでどちらを選ぶかはにへーさんにお任せします！
（もしくは素敵な代案が他の人からあれば…）

**Comment by yutonihei** [comment]
Marge後のTeamとかBlogを見た感じ、誰かがメンバーをTwitterのListでアカウントをまとめて、そのListのリンクを貼ればいいのでは？とも思ってきた。
（その人がアカウントを消したりスクリーンネームを変更しない前提）
代表アカウント作る案は、ありだと思うけど管理誰がするんだろう？って感じですかね。
代表アカウントを作れば、上記のListのURL問題は解消されるかな？とも。

**Comment by cocoeyes02** [comment]
> 誰かがメンバーをTwitterのListでアカウントをまとめて

現状作るならこれっぽい気がするなあ

ただ、それなら Contact はいらなくなりそう

**Comment by cocoeyes02** [comment]
新コンテンツ案を実施するので、こっちのissueはcloseします
