### ISSUE TITLE
ドメイン

### ISSUE THREAD

**Issue by IkezoeMakoto** [oystersjp/oystersjp.github.io#13]
ドメインどうするか。

・どういうドメイン名にするか
・費用の管理はどうするか
・アカウントはどうするか

**Comment by IkezoeMakoto** [comment]
現状は仮でgithub.ioでやってるので下記

oystersjp.github.io

**Comment by cocoeyes02** [comment]
https://chaos-boy.tokyo/posts/2018-05-29/github_pages_or_netrify_or_firebase/

> カスタムドメインだと、SSL証明書が自動で付与されない！

どうやら Github Pages だと、独自ドメインにすると別途 SSL 対応もする必要がありそうです

**Comment by cocoeyes02** [comment]
oysters.dev で登録した
費用はとりあえず 02 が出している
