### ISSUE TITLE
「勉強会」の英語表記は Study (Studies) でよいのか？

### ISSUE THREAD

**Issue by okashoi** [oystersjp/oystersjp.github.io#24]
なるほどー

案外 Events のままのほうが良かったり？あるいは Meetup とか Workshop とか？

まあこれは一旦 Issue にしておいて、ここでは Studies のまま進めましょか

_Originally posted by @okashoi in https://github.com/oystersjp/oystersjp.github.io/pull/18#issuecomment-489325272_

**Comment by cocoeyes02** [comment]
「勉強会」と「イベント」のドメインを整理したほうが良いかもですね…

勉強会
* どちらかというと身内向け
* 目的は、それぞれが勉強したい、知りたい、スキルアップしたいことを学ぶ。
* 例：scala 勉強会、ふるさと納税、履歴書・職歴書を書いたりする、「ボトムアップドメイン駆動開発」の資料を読む会 

イベント
* 外部の人も招くことが多い
* 目的は様々だが、勉強会よりも楽しむことが主体な感じあり
* 例：isucon （練習会）、無限 LT、サバゲ

**Comment by IkezoeMakoto** [comment]
個人的には

## 勉強会
* 目的: 勉強したい、ことものがある
* 外部の人を集客し辛いものもある

## イベント
* 目的: みんなであつまってわいわい、なにかをする
* 外部の人も集客しやすい

というイメージ

**Comment by mii288** [comment]
Tech events とか？

**Comment by mii288** [comment]
解決 #61
