### ISSUE TITLE
urlの#xxxxの文言合わせたい

### ISSUE THREAD

**Issue by klack710** [oystersjp/oystersjp.github.io#27]
以下の画像、http://localhost:1313/#studies
studiesってタグなのに、ページや文言はstudyになってる
他にもいろいろ。ただ、今後名前変更するだろうから、最後に合わせる感じでやりたい気持ち。

対応必須ではない。

<img width="1153" alt="スクリーンショット 2019-05-06 23 37 26" src="https://user-images.githubusercontent.com/10745640/57232639-fc5e1280-7057-11e9-92ad-0e66d5d342ce.png">

**Comment by cocoeyes02** [comment]
多分 #61 で日本語になったので不要
