### ISSUE TITLE
Metrics のコンテンツ作成

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/oystersjp.github.io#4]
Metrics のコンテンツ作成

_Originally posted by @cocoeyes02 in https://github.com/oystersjp/oystersjp.github.io/issues/3#issuecomment-487504041_

Study, Event, Development, 牡蠣食った数と下した数

### 梅
一旦仮で数字を置いておく（いわゆる仮実装）

### 竹
Study, Event, Development から API なり何なりで取得する
ただし、牡蠣食った数と下した数は定数のまま

### 松
Study, Event, Development から API なり何なりで取得する
牡蠣食った数と下した数をリアルタイム監視する機構を作る（ネタ）

**Comment by cocoeyes02** [comment]
これ数字がいくつかわかんねえな？
（牡蠣食った数と下した数はネタだから、適当に置くとしても）

外部公開は…
Study
Event
* 無限LT
Development 
* pengin news
* Coin Step

ぐらいなきがする
身内でやってるのはいっぱいある（僕が知らない範囲でも）
これ何でおけばいいんだろう

**Comment by IkezoeMakoto** [comment]
一旦2019以降とか、覚えてる範囲で良いのでは〜

**Comment by cocoeyes02** [comment]
> 2019以降、覚えてる範囲
そうですね、このくくりにしましょう！
であれば…

* Study（2019以降）
    * あれ？思い出せない…
* Event（2019以降）
    * isucon 練習会 3 回
    * 無限LT （身内1回、公開1回）2回
* Development（覚えている範囲）2つ
    * pengin news
    * Coin Step

**Comment by klack710** [comment]
Event→connpass限定にするなら、
https://connpass.com/api/v1/event/?series_id=7885
のresults_returnedの値で出来るね。

もしconnpass以外も含むなら、手動で更新していくことになるけど、
それなら結局手間変わらないし、梅で問題ない気がしている。

もし今後他の場所でもその値を使うなら、APIにしてもいいかも？

**Comment by IkezoeMakoto** [comment]
apiにするとしてどうやって反映する気持ちなんだろう。。？

**Comment by klack710** [comment]
画面に出す部分はJS書くつもりだった。

まあ一旦直書きで良い気がする_φ(･_･

**Comment by IkezoeMakoto** [comment]
>画面に出す部分はJS書くつもりだった。

なるほど

**Comment by cocoeyes02** [comment]
新コンテンツ案を実施するので、こっちのissueはcloseします
