### ISSUE TITLE
ロゴが欲しい

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/oystersjp.github.io#53]
ロゴ欲しい…欲しくない？

* ロゴ
* favicon

**Comment by okashoi** [comment]
ロゴを作る目的によるかなあ

**Comment by cocoeyes02** [comment]
外注する場合はお金必要だから、ロゴを作る意味は持たせたいですね

とはいえブランディング目的でやってるわけじゃないから、正直こんなん自己満足っすよ

自己満足でいくら出せるのかって話は、もちろんありますけどね

**Comment by mii288** [comment]
一旦今現在ロゴとして使われてる画像でfaviconとか設定したい気持ちです
_ロゴほしいけど外注に持ってくと永遠に完成しないと思われ（まとまらなさそう）_

**Comment by mii288** [comment]
こんなマイルストーンいかがでしょ？

1. 現在よく使われている黒字にOのアイコンをファビコンに設定
2. Oystersメンバー内でロゴ公募
3. 多数決で決定

2がそんなに集まらなかったらほしいやつでお金出し合って発注しよ！
（個人的にはみんなでひねって作ったロゴのほうがいいのができそうだと思ったりしてる）

**Comment by mii288** [comment]
@cocoeyes02 募集するものは以下のロゴかなと思っているんですがどうでしょ？

|#|項目|概要|例|
|----|----|----|----|
|1| ロゴマーク/ロゴタイプ|Oystersの文字が入ったもの|<img alt=GitHub_Logo src=https://user-images.githubusercontent.com/3056652/97276503-9df3a800-187a-11eb-8188-5612cffc9f57.png width=200 />|
|2| ロゴマーク/ロゴシンボル|正方形のもの|<img alt=GitHub-Mark-120px-plus src=https://user-images.githubusercontent.com/3056652/97276441-861c2400-187a-11eb-8fac-c4275b8fcc23.png width=60 />|

※それぞれ背景が黒/白のものを考えてもらう

FYI:
- http://brandesign.jp/about-lo-ma.html
- https://takashimaeda.jp/nasu-note/whatis_logo/

あと、参加してくれた人と採用された人にちょっとしたプレゼントみたいなものして企画自体を盛り上げたいな

**Comment by cocoeyes02** [comment]
@mii288  そうですね！その二つかと！

> 参加してくれた人と採用された人にちょっとしたプレゼントみたいなものして企画自体を盛り上げたいな

いいですね！採用されたロゴを使ったノベルティをプレゼントとか？

**Comment by mii288** [comment]
> いいですね！採用されたロゴを使ったノベルティをプレゼントとか？

ちょっと大変なので。Amazonギフト券でいいかな
とか思ってるけど、Slackでチャンネル作るね〜

ロゴを使ったオリジナルのアイテム作成は別でやるのもいいね

**Comment by mii288** [comment]
@pinkumohikan @IkezoeMakoto ?
今使ってるOystersのロゴマーク画像共有してほしい気持ち 👩‍🍳

**Comment by IkezoeMakoto** [comment]
oystersのslackに設定されてる画像を拾ってきた（元画像は多分適当に設定したので多分紛失した）
![oysters](https://user-images.githubusercontent.com/7962629/97296338-e1a6db80-1893-11eb-8142-02d17df1fd27.png)

**Comment by mii288** [comment]
アイコンと文字部分のバランスを調整しました。

[logo.zip](https://github.com/oystersjp/oystersjp.github.io/files/5482563/logo.zip)

<img src=https://user-images.githubusercontent.com/3056652/97997916-d4a66100-1e2c-11eb-839f-a0648717e684.png width=125 />
<img src=https://user-images.githubusercontent.com/3056652/98010710-59e44280-1e3a-11eb-99f0-09697b32f13e.png width=250 />

**Comment by mii288** [comment]
こっちでロゴのデータを管理することにしました。
https://github.com/oystersjp/brand

**Comment by mii288** [comment]
### TODO

- [x] 公式サイト更新 @mii288 

Thanks!
- [x] Github Organization
- [x] Scrapbox
- [x] Connpass
- [x] Slack

**Comment by mii288** [comment]
#67 更新したのでクローズします
