### ISSUE TITLE
保守用のドキュメントを用意したい

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/oystersjp.github.io#57]
忘れても手を加えやすいように、markdownに書いておきたい
* どのディレクトリにどんなファイルのがあるのか
* ファイルをいじるとどう変わるのか

**Comment by cocoeyes02** [comment]
#45 が終わったら書く

**Comment by YuMuuu** [comment]
これって今も生きているissueですかね？
nextjsにしたので開発環境&デプロイ環境のエコシステムが整ってパット見でも分かりやすいと思います。
componentがどこにあるか、はあっても良い気もします。

**Comment by cocoeyes02** [comment]
これnextjsにする前に立てたissueっすね

メンバーの追加方法等最低限のドキュメントはあるので、closeしちゃいましょ

> componentがどこにあるか

これはあると嬉しいっすね！けどこのissueもだいぶ古いので、必要なら別issueで立てましょ！
