### ISSUE TITLE
Study のコンテンツ作成

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/oystersjp.github.io#6]
Study のコンテンツ作成

_Originally posted by @cocoeyes02 in https://github.com/oystersjp/oystersjp.github.io/issues/3#issuecomment-487504370_

### 梅
羅列（いわゆる仮実装）

### 竹
別途勉強会を管理するプラットフォームを使い、そこからAPI取得をする

### 松
そんなものはない

**Comment by okashoi** [comment]
https://github.com/oystersjp/neta-note/issues?q=is%3Aopen+is%3Aissue

↑に勉強会用のラベルを作ってそのリンクにする、というのはどうだろう？

（GitHub 運用する前のものは含まれないけど）

**Comment by okashoi** [comment]
> GitHub 運用する前のもの

当時の履歴管理スプレッドシートも発見した

これをもとに過去開催したものも  issue に起こして `is:issue is:closed label:study` みたいな条件で絞り込めば

**Comment by cocoeyes02** [comment]
おお、良さげですね

**Comment by okashoi** [comment]
こんな感じで

https://github.com/oystersjp/neta-note/issues?q=is%3Aclosed+is%3Aissue+label%3Astudy

まだ issue 化されてない活動は後で issue に起こすとして、いったん

**Comment by okashoi** [comment]
いっそ Events と同じセクションにしてしまっていいんじゃないか？とも思った

**Comment by cocoeyes02** [comment]
neta-noteのリンクが貼ってあるのでいったんclose
