### ISSUE TITLE
Easy Playing にどんな画像載せるか検討

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/oystersjp.github.io#60]
Easy Playing にどんな画像載せようかな？

がっつり遊んでる感じの写真を載せたい

* ダーツ
* サバゲ
* スノボ

**Comment by mii288** [comment]
何が正しい分からないのだけど、easy play は検索しても使用例が見当たらなかったので、タイトルを変えた方が良さそう。

このコンテンツの場合だと Gatherings か 何某meet-up が適当？
FYI https://eikaiwa.dmm.com/uknow/questions/50203/

**Comment by cocoeyes02** [comment]
easy listening的なノリでeasy playingって書いた気が...確かにあんましない単語かも

個人的には人との交流をメインにした単語よりも、本当に遊ぶことを目的にした単語にしたい気持ちはあります！

なので単語的にはhang outとかほうがいいのかな...？
この辺はぜひ皆さんの意見が欲しいです！
https://eikaiwa.dmm.com/uknow/questions/51022/

**Comment by okashoi** [comment]
バーチャルな活動についても載せられれば

https://oystersjp.slack.com/archives/CU6LPMYMU

**Comment by cocoeyes02** [comment]
#74 で対応したのでclose
