### ISSUE TITLE
見出しを全て日本語にする提案

### ISSUE THREAD

**Issue by mii288** [oystersjp/oystersjp.github.io#61]
英語の翻訳がちょっと難しいので日本語で書くのはいかがでしょうか。

関連：
- #34
- #24

**Comment by cocoeyes02** [comment]
確かに元のテンプレートが英語だったのでそのままにしてましたが、無理に英語にこだわる必要ないですね…！

**Comment by cocoeyes02** [comment]
日本語にしたった :hahha-:

**Comment by mii288** [comment]
解決 #34
解決 #24
