### ISSUE TITLE
チームメンバー紹介コンテンツを再検討

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/oystersjp.github.io#62]
メンバー紹介コンテンツはgithubのorganizationの参加リスト貼り付けてたんですが...正直一部しか参加してないのであんまし紹介コンテンツとしては機能してないですね...！

そもそもこの辺新しい人が入るたびに追加する運用するのか？とか色々思うこともあって、ちゃんと紹介したい！って要望がなければ一旦消してしまおうかなと思って消してます！

この辺はいいアイデアがあれば求む！って感じです！

_Originally posted by @cocoeyes02 in https://github.com/oystersjp/oystersjp.github.io/pull/59#issuecomment-723590164_

**Comment by IkezoeMakoto** [comment]
scrapboxにページ作ってもらうとか？

https://scrapbox.io/oystersjp/members

**Comment by mii288** [comment]
新メンバー1年に1−2人しかいなさそうなので、更新の手間もそんなになさそう
最悪項目決めて入ってきた人にPR出してもらうとかでもいいかも

とりあえず希望者の↓載せるでいいんでない？
- 名前
- アイコン
- 職種
- SNS・ブログのURL

**Comment by mii288** [comment]
ジャストアイデアですけど、
タグクラウド載せたら、どんな人がいるのかパット見でわかりやすい？
