### ISSUE TITLE
Event のコンテンツ作成

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/oystersjp.github.io#7]
Event のコンテンツ作成

_Originally posted by @cocoeyes02 in https://github.com/oystersjp/oystersjp.github.io/issues/3#issuecomment-487504511_

### 梅
connpass のリンクを貼っておく（いわゆる仮実装）

### 竹
connpass の API を叩いて一覧表示

### 松
そんなものはない

**Comment by IkezoeMakoto** [comment]
APIだと更新しないといつまで立っても一覧が古いままになるので、一旦梅コースでいいかなって思った。
どんなイベントやってるかとか説明を付けてもいいかもしれない

**Comment by cocoeyes02** [comment]
一旦梅コースで実装したのでclose

さらに進化させるとなったら再openする
