### ISSUE TITLE
Team のコンテンツ作成

### ISSUE THREAD

**Issue by cocoeyes02** [oystersjp/oystersjp.github.io#9]
Team のコンテンツ作成

_Originally posted by @cocoeyes02 in https://github.com/oystersjp/oystersjp.github.io/issues/3#issuecomment-487504733_

### 梅
Github Organization へのリンクを貼る

### 竹
別途メンバー紹介ページを用意し、そのリンクを貼る

### 松
その他何か

**Comment by BBCapMegane** [comment]
梅でいいと思う

メンバーの紹介ページは↓でよさそう
https://github.com/orgs/oystersjp/people

各メンバー分作るのはかっこいいけど、メンバー全員分の作成と、
追加時のことを考えると現実的でない
ちょっと作ってみた↓
![team mov](https://user-images.githubusercontent.com/28012205/57233952-a2ab1780-705a-11e9-8ecf-adae441c9277.gif)

**Comment by cocoeyes02** [comment]
梅が達成できているので一旦close

もっと進化するってことになったら再 open しよう
